config/routes.rb
Rails.application.routes.draw do

  root "homes#index"
  resource :homes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email,:name , presence: true
  validates  :email , uniqueness: true
  has_many :user_payments
end

app/models/user_payment.rb
class UserPayment < ApplicationRecord
  belongs_to :user
  enum status:  { unpaid: "unpaid", missing: "missing" ,paid: "paid", canceled: "canceled"}

  scope :paid_count,  -> { where(status: "unpaid").count}
  scope :missing_count,  -> { where(status: "missing").count}
  scope :un_paid_count,  -> { where(status: "unpaid").count}
  scope :canceled_count,  -> { where(status: "canceled").count}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user =  User.find(params[:id]) if params[:id].present?
    return unless @user
    @payment_history = [
      {status: "canceled" ,data: @user.user_payments.canceled},
      {status: "paid" ,data: @user.user_payments.paid},
      {status: "unpaid" ,data: @user.user_payments.unpaid},
      {status: "missing" ,data: @user.user_payments.missing}
    ]

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def get_paid_count(single_data)
    single_data.user_payments.paid_count
  end

  def get_unpaid_count(single_data)
    single_data.user_payments.un_paid_count
  end

  def get_canceled_count(single_data)
    single_data.user_payments.canceled_count
  end

  def get_missing_count(single_data)
    single_data.user_payments.missing_count
  end
end

app/views/homes/index.html.erb
<% if @user.present? %>
    <table>
      <thead>
        <th>Name</th>
         <th>Email</th>
        <th>Paid Count</th>
        <th>UN Paid Count</th>
        <th>Canceled Count</th>
        <th>Missing Count</th>
         <th>Show User Payment History</th>
      </thead>
      <tbody>
      <% @user.each do |single_data| %>
        <tr>
            <td><%=single_data[:name] %></td>
            <td><%= single_data[:email] %></td>
            <td><%= get_paid_count(single_data) %></td>
            <td><%= get_unpaid_count(single_data)%></td>
            <td><%= get_canceled_count(single_data) %></td>
            <td><%= get_missing_count(single_data) %></td>
            <td><%= link_to "Full Payment History", homes_path(id: single_data[:id]) %></td>
        </tr>
      <%end %>
      </tbody>
    </table>
<%else%>
     <h1>Please send the data</h1>
<%end%>

app/views/homes/show.html.erb
<% if @user.present? %>
   <h1><%= @user.name %></h1>
  <h6><%= @user.email %></h6>
  <% if @payment_history.present? %>
       <% @payment_history.each do |single_payment_status| %>
         <h1><%= single_payment_status[:status] %></h1>
          <table>
             <thead>
             <th>Order ID</th>
             <th>Order Date</th>
             <th>Received Date</th>
             <th>status</th>
             </thead>
          <% if single_payment_status[:data] %>
               <tbody>
                <% single_payment_status[:data].each do |item| %>

                  <tr>
                    <td><%= item[:id] %></td>
                    <td><%= item[:order_date] %></td>
                    <td><%= item[:received_date] %></td>
                    <td><%= item[:status] %></td>
                  </tr>
                <%end %>
               </tbody>
          <%end%>
          </table>
       <%end%>
  <%end%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobInterview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>